export const routes = {
  home: "/",
  products: "/products",
  clothes: "/clothes",
  cart: "/cart",
  checkout: "/checkout",
  login: "/login",
  register: "/register",
  about: "/about",
  contact: "/contact",
  faq: "/faq",
  privacy: "/policies/privacy",
  terms: "/policies/terms",
  shippingReturns: "/policies/shipping-returns",
  accountProfile: "/account/profile",
  accountOrders: "/account/orders",
  admin: "/admin",
  adminProducts: "/admin/products",
  adminOrders: "/admin/orders",
  adminPages: "/admin/pages",
  adminPayments: "/admin/payments",
  adminSocial: "/admin/social",
} as const;
